### ISSUE TITLE
Please add examples where the step definition functions are async and there are multiple 'when' steps

### ISSUE THREAD

**Issue by albinocordeiro** [sitegeist/gherkin-testcafe#1]
I'm suspecting there is a bug when one has multiple when steps defined by async functions. It seems the sequential when calls are not being awaited. If a bug doesn't exist, then an example on how to work with that situation would be much appreciated.

**Comment by tapesec** [comment]
Did you found an issue to this potential bug ?

**Comment by grebaldi** [comment]
Hey @albinocordeiro,

sorry for taking so long to respond.

I recently transferred maintenance of this package to @Lukas-Kullmann. The new repo can be found here: https://github.com/kiwigrid/gherkin-testcafe

I think your issue has been addressed there already. Maybe just checkout the latest release: https://www.npmjs.com/package/gherkin-testcafe

Have a nice day :)
