### ISSUE TITLE
Feature Request: Scenario Outline

### ISSUE THREAD

**Issue by csi-lk** [sitegeist/gherkin-testcafe#6]
It doesn't look like [Scenario Outlines](https://github.com/cucumber/cucumber/wiki/Scenario-Outlines) are supported...

For example...

login.feature

```
  Scenario Outline: I should be redirected if I am not authenticated
    Given I am on the "<page>" page
    Then I should be on the "login" page
    Examples:
      | page            |
      | client          |
```

login.steps.js

```javascript
  given('I am on the {string} page', async (t, pageName) => t
    .navigateTo(`http://localhost:8008/${pageName}`),
  )
```

Output

```
✖ Scenario: I should be redirected if I am not authenticated
   1) AssertionError: expected 'http://localhost:8008/%3Cpage%3E' to include undefined

Browser: HeadlessChrome 64.0.3282 / Mac OS X 10.13.3
```

**Comment by grebaldi** [comment]
Hey @csi-lk,

sorry for taking so long to respond.

I recently transferred maintenance of this package to @Lukas-Kullmann. The new repo can be found here: https://github.com/kiwigrid/gherkin-testcafe

I think your issue has been addressed there already. Maybe just checkout the latest release: https://www.npmjs.com/package/gherkin-testcafe

Have a nice day :)
